In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline 

In [2]:
iris_data = pd.read_csv("~/Desktop/Datasets/iris_data.csv")

In [3]:
iris_data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
features = iris_data.iloc[:, 0:4].values
labels = iris_data.iloc[:, 4].values

In [5]:
from sklearn.model_selection import train_test_split
train_features,test_features,train_labels,test_labels = train_test_split(features,labels,test_size = 0.2,random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler 
feature_scaler = StandardScaler()
train_features = feature_scaler.fit_transform(train_features)
test_features = feature_scaler.transform(test_features)

In [7]:
from sklearn.naive_bayes import GaussianNB
nb_clf = GaussianNB()
nb_clf.fit(train_features, train_labels)

GaussianNB()

In [8]:
predictions = nb_clf.predict(test_features)

In [9]:
comparison = pd.DataFrame({'Real':test_labels,'Predictions':predictions})

In [10]:
print(comparison)

          Real Predictions
0    virginica   virginica
1   versicolor  versicolor
2       setosa      setosa
3    virginica   virginica
4       setosa      setosa
5    virginica   virginica
6       setosa      setosa
7   versicolor  versicolor
8   versicolor  versicolor
9   versicolor  versicolor
10   virginica  versicolor
11  versicolor  versicolor
12  versicolor  versicolor
13  versicolor  versicolor
14  versicolor  versicolor
15      setosa      setosa
16  versicolor  versicolor
17  versicolor  versicolor
18      setosa      setosa
19      setosa      setosa
20   virginica   virginica
21  versicolor  versicolor
22      setosa      setosa
23      setosa      setosa
24   virginica   virginica
25      setosa      setosa
26      setosa      setosa
27  versicolor  versicolor
28  versicolor  versicolor
29      setosa      setosa


In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [12]:
print(confusion_matrix(test_labels, predictions))

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


In [13]:
print(classification_report(test_labels,predictions))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       0.93      1.00      0.96        13
   virginica       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30



In [14]:
print(accuracy_score(test_labels,predictions))

0.9666666666666667


In [ ]:
#97% accuracy!Boom!