In [48]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [49]:
petrol_data = pd.read_csv("Desktop/Datasets/petrol_data.csv")

In [50]:
petrol_data.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [51]:
petrol_data.describe()

Petrol_tax  Average_income  Paved_Highways  \
count   48.000000       48.000000       48.000000   
mean     7.668333     4241.833333     5565.416667   
std      0.950770      573.623768     3491.507166   
min      5.000000     3063.000000      431.000000   
25%      7.000000     3739.000000     3110.250000   
50%      7.500000     4298.000000     4735.500000   
75%      8.125000     4578.750000     7156.000000   
max     10.000000     5342.000000    17782.000000   

       Population_Driver_licence(%)  Petrol_Consumption  
count                     48.000000           48.000000  
mean                       0.570333          576.770833  
std                        0.055470          111.885816  
min                        0.451000          344.000000  
25%                        0.529750          509.500000  
50%                        0.564500          568.500000  
75%                        0.595250          632.750000  
max                        0.724000          968.000000

In [52]:
features = petrol_data[["Petrol_tax", "Average_income", "Paved_Highways", "Population_Driver_licence(%)", "Petrol_Consumption"]]

In [53]:
labels = petrol_data['Petrol_Consumption']

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.2, random_state = 0)

In [56]:
from sklearn.preprocessing import PolynomialFeatures

In [57]:
poly_reg_feat = PolynomialFeatures(degree=2)
train_features_poly = poly_reg_feat.fit_transform(train_features)
test_features_poly = poly_reg_feat.transform(test_features)

In [58]:
train_features_poly

array([[1.00000000e+00, 7.50000000e+00, 5.12600000e+03, 1.41860000e+04,
        5.25000000e-01, 4.71000000e+02, 5.62500000e+01, 3.84450000e+04,
        1.06395000e+05, 3.93750000e+00, 3.53250000e+03, 2.62758760e+07,
        7.27174360e+07, 2.69115000e+03, 2.41434600e+06, 2.01242596e+08,
        7.44765000e+03, 6.68160600e+06, 2.75625000e-01, 2.47275000e+02,
        2.21841000e+05],
       [1.00000000e+00, 7.00000000e+00, 3.33300000e+03, 6.59400000e+03,
        5.13000000e-01, 5.54000000e+02, 4.90000000e+01, 2.33310000e+04,
        4.61580000e+04, 3.59100000e+00, 3.87800000e+03, 1.11088890e+07,
        2.19778020e+07, 1.70982900e+03, 1.84648200e+06, 4.34808360e+07,
        3.38272200e+03, 3.65307600e+06, 2.63169000e-01, 2.84202000e+02,
        3.06916000e+05],
       [1.00000000e+00, 7.50000000e+00, 3.35700000e+03, 4.12100000e+03,
        5.47000000e-01, 6.28000000e+02, 5.62500000e+01, 2.51775000e+04,
        3.09075000e+04, 4.10250000e+00, 4.71000000e+03, 1.12694490e+07,
        1.3834

In [59]:
test_features_poly

array([[1.0000000e+00, 9.0000000e+00, 3.6010000e+03, 4.6500000e+03,
        4.9300000e-01, 5.3400000e+02, 8.1000000e+01, 3.2409000e+04,
        4.1850000e+04, 4.4370000e+00, 4.8060000e+03, 1.2967201e+07,
        1.6744650e+07, 1.7752930e+03, 1.9229340e+06, 2.1622500e+07,
        2.2924500e+03, 2.4831000e+06, 2.4304900e-01, 2.6326200e+02,
        2.8515600e+05],
       [1.0000000e+00, 8.0000000e+00, 4.3990000e+03, 4.3100000e+02,
        5.4400000e-01, 4.1000000e+02, 6.4000000e+01, 3.5192000e+04,
        3.4480000e+03, 4.3520000e+00, 3.2800000e+03, 1.9351201e+07,
        1.8959690e+06, 2.3930560e+03, 1.8035900e+06, 1.8576100e+05,
        2.3446400e+02, 1.7671000e+05, 2.9593600e-01, 2.2304000e+02,
        1.6810000e+05],
       [1.0000000e+00, 8.0000000e+00, 3.4480000e+03, 5.3990000e+03,
        5.4800000e-01, 5.7700000e+02, 6.4000000e+01, 2.7584000e+04,
        4.3192000e+04, 4.3840000e+00, 4.6160000e+03, 1.1888704e+07,
        1.8615752e+07, 1.8895040e+03, 1.9894960e+06, 2.9149201e+07,


In [60]:
from sklearn.preprocessing import StandardScaler
feature_scaler = StandardScaler()
train_features_poly = feature_scaler.fit_transform(train_features_poly)
test_features_poly = feature_scaler.transform(test_features_poly)

In [61]:
from sklearn.linear_model import LinearRegression 
lin_reg = LinearRegression()
lin_reg.fit(train_features_poly, train_labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [62]:
predictions = lin_reg.predict(test_features_poly)

In [63]:
comparison=pd.DataFrame({'Real':test_labels, 'Predictions':predictions})

In [64]:
print(comparison)

    Real  Predictions
29   534        534.0
4    410        410.0
26   577        577.0
30   571        571.0
32   577        577.0
37   704        704.0
34   487        487.0
40   587        587.0
7    467        467.0
10   580        580.0


In [43]:
predictions = lin_reg.predict(test_features_poly) 

In [44]:
predictions 

array([534., 410., 577., 571., 577., 704., 487., 587., 467., 580.])

In [45]:
test_labels

29    534
4     410
26    577
30    571
32    577
37    704
34    487
40    587
7     467
10    580
Name: Petrol_Consumption, dtype: int64

In [46]:
from sklearn import metrics 

In [47]:
print('MAE:', metrics.mean_absolute_error(test_labels, predictions))
print('MSE:', metrics.mean_squared_error(test_labels, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels, predictions)))

MAE: 8.526512829121202e-14
MSE: 1.1955344790805479e-26
RMSE: 1.0934049931660948e-13
